# Generated by Django 4.2.3 on 2023-07-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_producto_facturaid_alter_detallefactura_productoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
